name: MinecraftDay
version: @version@
main: jp.minecraftday.minecraftinstrumentality.Main
api-version: 1.13

commands:
  md:
    description: サーバーセッティング
    usage: "使用例: /<command> [welcome]"
    permission: minecraftday.md
    permission-message: 使用する権利がありません <permission>
  md welcome:
    description: ログインメッセージを設定
    permission: minecraftday.md.welcome
    usage: "使用例: /<command> メッセージ"
    permission-message: 使用する権利がありません <permission>
  minigame:
    description: ミニゲーム
    aliases: mg
    usage: "使用例: /<command> [set|start|invite|list|cancel|join|gather|finish]"
    permission: minecraftday.mg
    permission-message: 使用する権利がありません <permission>
  minigame set:
    description: ゲームの設定
    permission: minecraftday.mg
    usage: "使用例: /<command> 分"
  minigame start:
    description: ゲームスタート
    permission: minecraftday.mg
    usage: "使用例: /<command>"
  minigame invite:
    description: ゲームへの招待
    permission: minecraftday.mg
    usage: "使用例: /<command> プレイヤー名"
  minigame list:
    description: ゲームの参加者を表示
    permission: minecraftday.mg
    usage: "使用例: /<command>"
  minigame cancel:
    description: ゲームキャンセル
    permission: minecraftday.mg
    usage: "使用例: /<command>"
  minigame join:
    description: ゲームへの参加
    permission: minecraftday.mg
    usage: "使用例: /<command> [ゲーム番号]"
  minigame gather:
    description: プレイヤーの集合
    permission: minecraftday.mg.gather
    usage: "使用例: /<command>"
  minigame finish:
    description: ゲームから離脱
    permission: minecraftday.mg
    usage: "使用例: /<command>"
  setitem:
    usage: "使用例: /<command> [name|lore]"
    permission: minecraftday.sn
    permission-message: 使用する権利がありません <permission>
permissions:
  minecraftday.md:
    description: サーバー設定コマンドのパーミッション
    default: op
  minecraftday.mg:
    description: ミニゲームコマンドのパーミッション
    default: true
  minecraftday.mg.gather:
    description: 集合コマンドのパーミッション
    default: op
  minecraftday.setitem:
    description: ミニゲームコマンドのパーミッション
    default: true
