name: MinecraftDay
version: @version@
main: jp.minecraftday.minecraftinstrumentality.Main
api-version: 1.13

commands:
  md:
    description: Server Setting
    usage: "Usage: /<command> [welcome|reload]"
    permission: minecraftday.md
    permission-message: You dont't have <permission>
  minigame:
    description: mini game
    aliases: mg
    usage: "Usage: /<command> [set|start|invite|list|cancel|join|gather|finish]"
    permission: minecraftday.mg
    permission-message: You dont't have <permission>
  minigame set:
    description: game settings
    permission: minecraftday.mg
    usage: "Usage: /<command> min"
  minigame start:
    description: start game
    permission: minecraftday.mg
    usage: "Usage: /<command>"
  minigame invite:
    description: invite game
    permission: minecraftday.mg
    usage: "Usage: /<command> player name"
  minigame list:
    description: list of players
    permission: minecraftday.mg
    usage: "Usage: /<command>"
  minigame cancel:
    description: cancel game
    permission: minecraftday.mg
    usage: "Usage: /<command>"
  minigame join:
    description: join game
    permission: minecraftday.mg
    usage: "Usage: /<command> [game no]"
  minigame gather:
    description: gather players
    permission: minecraftday.mg.gather
    usage: "Usage: /<command>"
  minigame finish:
    description: finish game
    permission: minecraftday.mg
    usage: "Usage: /<command>"
  setitem:
    usage: "Usage: /<command> [name|lore]"
    permission: minecraftday.setitem
    permission-message: You dont't have <permission>
  vote:
    usage: "Usage: /<command> [day|night|sun|rain|jail|unjail|mute|ummute|yes|no]"
    permission: minecraftday.vote
    permission-message: You dont't have <permission>
  vote jail:
    usage: "Usage: /<command> jail"
    permission: minecraftday.vote.jail
    permission-message: You dont't have <permission>
  vote mute:
    usage: "Usage: /<command> mute"
    permission: minecraftday.vote.mute
    permission-message: You dont't have <permission>
  voteyes:
    usage: "Usage: /<command>"
    permission: minecraftday.vote.yes
    permission-message: You dont't have <permission>
  voteno:
    usage: "Usage: /<command>"
    permission: minecraftday.vote.no
    permission-message: You dont't have <permission>
permissions:
  minecraftday.md:
    description: server settings permission
    default: op
  minecraftday.mg:
    description: minigame permission
    default: true
  minecraftday.mg.gather:
    description: gather command permission
    default: op
  minecraftday.setitem:
    description: itemname command permission
    default: true
  minecraftday.vote:
    description: vote command permission
    default: true
  minecraftday.vote.jail:
    description: jail command permission
    default: op
  minecraftday.vote.mute:
    description: mute command permission
    default: op
  minecraftday.vote.yes:
    description: voteyes command permission
    default: true
  minecraftday.vote.no:
    description: voteno command permission
    default: true
