#TNTを無効にするワールド
tntcanceller:
  worlds: []
#ログイン時のメッセージ
welcome:
  message: '[{"text":"Welcome to the MinecraftDay Server!"}]'
#Jailでいれる部屋の名前
vote:
  jailname: test
#毎月定額で入金されるお金
basicincome:
  money: 5000
#毎月定額で入金されるお金
ng:
  cooldown: 15
  maxtime: 3600
  words:
    - しね
    - 死ね